org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=false

org.gradle.configuration-cache=false
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

net.minecraftforge.gradle.merge-source-sets=true

## Environment Properties

minecraft_version=1.7.10
forge_version=10.13.4.1614-1.7.10
