# RetroFuturaBootstrap plugin property file
# All properties can be empty or missing, unless specified otherwise. Lists are semicolon-separated, and whitespace
# around each value is stripped, unless specified otherwise.
# Human-friendly name (required). Only used for logging, all logic uses the plugin ID (taken from the file name).
name=MonoMixins
# A Maven-compatible version number, used for validating dependencies and detecting duplicates (required)
version=${projectVersion}
# The class implementing com.gtnewhorizons.retrofuturabootstrap.api.RfbPlugin (required)
className=io.github.legacymoddingmc.unimixins.compat.rfb.MonoMixinsRfbPlugin
